---
- hosts: all
  become: true
  tasks: 
    - name: Install Docker Module for Python
      pip:
        name: docker

    - name:  Pull elasicsearch Docker image
      docker_image:
        name: "docker.elastic.co/elasticsearch/elasticsearch:7.9.0"
        source: pull

    - name: Create elasticsearch container
      docker_container:
        name: "elasticsearch"
        image: "docker.elastic.co/elasticsearch/elasticsearch:7.9.0"
        exposed: "9200, 9300"
        state: started

    - name: Pull kibana Docker image
      docker_image:
        name: "docker.elastic.co/kibana/kibana:7.9.0"
        source: pull

    - name: Create kibana container
      docker_container:
        name: "kibana"
        image: "docker.elastic.co/kibana/kibana:7.9.0"
        links: "elasticsearch:elasticsearch"
        state: started
        exposed: "5601"
